In [29]:
import pandas as pd
import numpy as np

In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
df = pd.read_csv("/content/drive/MyDrive/Group 11 /hour.csv")
df

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [32]:
df.shape

(17379, 17)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

In [34]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [35]:
df.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [38]:
df["dteday"] = pd.to_datetime(df["dteday"])

print(df["dteday"].dtype)

datetime64[ns]

In [39]:
invalid_hr = ((df["hr"] < 0) | (df["hr"] > 23)).sum()

print("Invalid hour values:", invalid_hr)

Invalid hour values: 0

In [40]:
invalid_hum = ((df["hum"] < 0) | (df["hum"] > 1)).sum()

print("Invalid humidity values:", invalid_hum)

Invalid humidity values: 0

In [41]:
invalid_temp = ((df["temp"] < 0) | (df["temp"] > 1)).sum()

print("Invalid temperature values:", invalid_temp)

Invalid temperature values: 0

In [42]:
invalid_wind = ((df["windspeed"] < 0) | (df["windspeed"] > 1)).sum()

print("Invalid windspeed values:", invalid_wind)

Invalid windspeed values: 0

In [43]:
Q1 = df["cnt"].quantile(0.25)
Q3 = df["cnt"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["cnt"] < lower_limit) |
    (df["cnt"] > upper_limit)
]

print("Number of potential outliers:", len(outliers))

Number of potential outliers: 505

In [44]:
df = df.sort_values(
    by=["dteday", "hr"]
).reset_index(drop=True)

print(df.head())

   instant     dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1 2011-01-01       1   0     1   0        0        6           0
1        2 2011-01-01       1   0     1   1        0        6           0
2        3 2011-01-01       1   0     1   2        0        6           0
3        4 2011-01-01       1   0     1   3        0        6           0
4        5 2011-01-01       1   0     1   4        0        6           0

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt
0           1  0.24  0.2879  0.81        0.0       3          13   16
1           1  0.22  0.2727  0.80        0.0       8          32   40
2           1  0.22  0.2727  0.80        0.0       5          27   32
3           1  0.24  0.2879  0.75        0.0       3          10   13
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [45]:
target = "cnt"

In [46]:
print(df[target].head())

0    16
1    40
2    32
3    13
4     1
Name: cnt, dtype: int64

In [47]:
df.to_csv("/content/drive/MyDrive/Group 11 /cleaned_bike_sharing.csv", index=False)

In [48]:
X = df.drop(columns=["cnt", "casual", "registered"])
y = df["cnt"]

In [49]:
print("Features:", X.shape)
print("Target:", y.shape)

Features: (17379, 14)
Target: (17379,)

In [50]:
split_index = int(len(df) * 0.8)

train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

print("Training rows:", len(train_df))
print("Testing rows:", len(test_df))

Training rows: 13903
Testing rows: 3476

In [51]:
X_train = train_df.drop(columns=["cnt", "casual", "registered"])
y_train = train_df["cnt"]

X_test = test_df.drop(columns=["cnt", "casual", "registered"])
y_test = test_df["cnt"]

In [52]:
X_train = X_train.drop(columns=["dteday"])
X_test = X_test.drop(columns=["dteday"])

In [53]:
numeric_features = [
    "temp",
    "atemp",
    "hum",
    "windspeed"
]

In [54]:
categorical_features = [
    "season",
    "yr",
    "mnth",
    "hr",
    "holiday",
    "weekday",
    "workingday",
    "weathersit"
]

In [55]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

In [56]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [57]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [58]:
preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

In [59]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)
print("Training processed shape:", X_train_processed.shape)
print("Testing processed shape:", X_test_processed.shape)

Training processed shape: (13903, 61)
Testing processed shape: (3476, 61)

In [60]:
X_train_processed = preprocessor.fit_transform(X_train)

In [61]:
X_test_processed = preprocessor.transform(X_test)

In [62]:
feature_names = preprocessor.get_feature_names_out()

X_train_processed_df = pd.DataFrame(
    X_train_processed.toarray(),
    columns=feature_names
)

X_test_processed_df = pd.DataFrame(
    X_test_processed.toarray(),
    columns=feature_names
)

In [63]:
X_train_processed_df["cnt"] = y_train.values
X_test_processed_df["cnt"] = y_test.values

In [64]:
X_train_processed_df.to_csv("train_features.csv", index=False)

X_test_processed_df.to_csv("test_features.csv", index=False)

In [65]:
quality_log = {
    "Rows": len(df),
    "Columns": len(df.columns),
    "Missing Values": int(df.isnull().sum().sum()),
    "Duplicate Rows": int(df.duplicated().sum()),
    "Invalid Hour Values": int(((df["hr"] < 0) | (df["hr"] > 23)).sum())
}

quality_df = pd.DataFrame([quality_log])

print(quality_df)

    Rows  Columns  Missing Values  Duplicate Rows  Invalid Hour Values
0  17379       17               0               0                    0

In [66]:
quality_df.to_csv("data_quality_log.csv", index=False)